use_frameworks!

platform :ios, '9.0'

target 'XSJZjhTestLogin_Example' do
  pod 'XSJZjhTestLogin', :path => '../'

  target 'XSJZjhTestLogin_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
