use_frameworks!

platform :ios, '9.0'

target 'XSJZjhTestLogin_Example' do
  pod 'XSJZjhTestLogin', :path => '../'
  pod 'XSJZjhTestNetworking' , :path => '../../XSJZjhTestNetworking'
  
  #pod 'AFNetworking', '~> 2.3'

  target 'XSJZjhTestLogin_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
